<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>QuickDiscard</AssemblyName>
    <RootNamespace>QuickDiscard</RootNamespace>
    <LangVersion>5</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GameDir Condition="'$(GameDir)' == ''">D:\free games\EFT_0821</GameDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="netstandard">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\ItemComponent.Types.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ItemTemplate.Types">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\ItemTemplate.Types.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(GameDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameDir)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\Sirenix.OdinInspector.Attributes.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\Sirenix.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
